---
- name: Install Redis Server
  hosts: testserver01
  become: true
  tasks:
    - name: Install Redis dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop: #YOU CAN WITH_ITEMS ALSO
        - build-essential #THESE ARE TWO PACKAGES TO BE INSTALLED.
        - tcl
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04' #UNLESS THIS NOT MATCHING THE ABOVE WILL NOT BE INSTALLED

    - name: Check Redis Status #CHECKING THE STATUS
      shell: systemctl status redis --no-pager
      register: redis_status # we are going to use the systemctl output as register: redis status and We are ignoring.
      ignore_errors: true

    - name: Download and extract Redis source code
      get_url:
        url: "http://download.redis.io/releases/redis-6.2.5.tar.gz"
        dest: "/tmp/redis.tar.gz"
      #delegate_to: localhost
      when: redis_status.rc != 0

    - name: Extract Redis source code
      unarchive:
        src: "/tmp/redis.tar.gz"
        dest: "/tmp"
        remote_src: yes #IF YOU ARE NOT GIVING REMOTE_SORUCE: YES --> ITS GOING TO CHECKIN LOCAL
      when: redis_status.rc != 0

    - name: Compile and install Redis #
      shell: |
        cd /tmp/redis-6.2.5 
        make
        make install
      args:
        executable: /bin/bash
      when: redis_status.rc != 0
      #WE ARE GOING INTO THIS FODLER AND INSTALLING MAKE AND WE ARE EXECUTING ALL COMMANDS IN BIN/BASH

    - name: Configure Redis
      copy:
        src: redis.conf
        dest: /etc/redis.conf
        owner: root
        group: root
        mode: "0644"
      #when: redis_status.rc != 0
      notify: #THESE WERE CALLED AS HANDLERS.
        - Restart Redis
        - Backup Redis Conf File
        - Download Redis Backup Config File Flat
        - Download Redis Backup Config File Without Flat

    - name: Create Redis systemd service
      copy:
        src: redis.service
        dest: /etc/systemd/system/redis.service
        owner: root
        group: root
        mode: "0644"
      #when: redis_status.rc != 0
      notify:
        - Restart Redis
        - Backup Redis Conf File

    - name: Start Redis service
      systemd:
        name: redis
        state: started
        enabled: yes
      when: redis_status.rc != 0

    - name: Checking Deligate Option
      shell: hostname
      delegate_to: localhost #or 127.0.0.1

  handlers:
    - name: Backup Redis Conf File
      shell: rm -rf /tmp/redis.conf_backup && cp /etc/redis.conf /tmp/redis.conf_backup #WE ARE TAKING THE BACKUP OF THE CONFIG FILE

    - name: Restart Redis
      systemd:
        name: redis
        state: restarted

    - name: Download Redis Backup Config File Flat
      fetch:
        src: /tmp/redis.conf_backup
        dest: /tmp/redis.conf_backup-{{ inventory_hostname }}
        flat: yes
    - name: Download Redis Backup Config File Without Flat #We are downloading the config file to the Local Location.
      fetch:
        src: /tmp/redis.conf_backup
        dest: /tmp/
        #flat: yes  #This will download whole path of the file.
